config {
    type: "table",
    database: "gds-bq-reporting",
    schema: "publishing_zendesk",
    assertions: {},
    description: "test output before moving to govuk-publishing"
}

SELECT
  id,
  created_at,
  updated_at,
  type,
  subject,
  description,
  priority,
  status,
  assignee_id,
  requester_id,
  submitter_id,
  recipient,
  organization_id,
  due_at,
  tags,
  group_name AS group_id
FROM
  ${ref("modifying_group_names")}
