config {
  type: "view",
}

-- pre_operations {
--   DECLARE partition_id DATE;
--   SET partition_id = (
--     SELECT COALESCE(PARSE_DATE("%Y%m%d", MAX(partition_id)), DATE('1900-01-01'))
--     FROM ${ref("ga4_process_partition")}
--     );
-- }
SELECT 
id,
created_at,
updated_at,
ticket
FROM
 `govuk-knowledge-graph.zendesk.tickets`

-- WHERE TIMESTAMP_TRUNC(updated_at, DAY) > TIMESTAMP("2025-11-10")